### ISSUE TITLE
Hourglass model

### ISSUE THREAD

**Issue by edvardHua** [tucan9389/PoseEstimation-CoreML#1]
Try to use hourglass model in [here](https://github.com/edvardHua/PoseEstimationForMobile/tree/master/release/hourglass_model).

* input_image_shape: [1, 192, 192, 3]
* output_shape: [1, 48, 48, 14]
* input_node_name: image
* output_node_name: hourglass_out_3

I think it will speed up 3x than old model and the precision is acceptable.

Tomorrow I will update my repo.

Look forward to your replay ( ? FPS on ipx )

**Comment by tucan9389** [comment]
@edvardHua  AWESOME! I'll try that model 👍 
Do you have a python script that converts to Core ML model?
I have some issue in converting my own model to Core ML now 😓

**Comment by edvardHua** [comment]
Yes, I will let you know when I update repo tomorrow.

**Comment by tucan9389** [comment]
@edvardHua I capture video comparing two models.
but It's little weird for accuracy.

model | cpm model | hourglass model
------------ | ------------ | -------------
inference time | 57(45~70)mm | **33(30~35)mm**
accuracy | more accurate(0.9) | **less accurate(<0.5)**
DEMO video | ![poseestimation-coreml-cpm](https://user-images.githubusercontent.com/37643248/42610042-88c3c270-85ca-11e8-8d45-e99c97514de7.gif) | ![poseestimation-coreml-hourglass](https://user-images.githubusercontent.com/37643248/42610043-8906a3c4-85ca-11e8-9dc4-8cc160f98d1d.gif)

**Comment by edvardHua** [comment]
Indeed, the old one have precision is higher than the new one.

```
PCKh of cpm model is 94.18.
PCKh of hourglass model is 91.
```

But hourglass do not have too wide difference on android device.

**You can test android demo [here](https://fir.im/vhs7)**

**Comment by edvardHua** [comment]
@tucan9389 [Here](https://github.com/edvardHua/PoseEstimationForMobile/blob/master/training/src/gen_tflite_coreml.py) is the script I used to convert mlmodel.

**Comment by tucan9389** [comment]
Thanks a lot

**Comment by tucan9389** [comment]
Unfortunately I can’t open my models. If you want compare between cpm and hourglass model, you can download from [here](https://github.com/edvardHua/PoseEstimationForMobile/tree/master/release).

**Comment by tucan9389** [comment]
Close the issue now. You can reopen when you want. @edvardHua
