### ISSUE TITLE
Why did you add 0.5 when transpose predicted point to (1.0, 1.0)? What is 0.5? 

### ISSUE THREAD

**Issue by KrasnikovRoman** [tucan9389/PoseEstimation-CoreML#18]

**Comment by tucan9389** [comment]
Could you tell me the code location of `0.5`?

**Comment by KrasnikovRoman** [comment]
/Common/HeatmapPostProcessor.swift -> Method convertToPredictedPoints -> lines 43 and 44.

**Comment by tucan9389** [comment]
> Why did you add 0.5 when transpose predicted point to (1.0, 1.0)? 

The following comment is mistyped 🤯
```
// transpose to (1.0, 1.0)
```

> What is 0.5?

It's kind of location correction. Each location move to the middle of the box.

**Comment by KrasnikovRoman** [comment]
Thank you!
