### ISSUE TITLE
How show in front camera?

### ISSUE THREAD

**Issue by Tsepu** [tucan9389/PoseEstimation-CoreML#22]
I am tried this project. I am using with front camera, but when i move left hand, the right hand of model moves. It is like mirror. How to fix it?

**Comment by tucan9389** [comment]
You can check [this line](https://github.com/tucan9389/PoseEstimation-CoreML/blob/b898bbf19afcf29cfadb30cc6c6ed0c86c2554c2/PoseEstimation-CoreML/Pose%20Matching%20View%20Controller/PoseMatchingViewController.swift#L180). Maybe you should change the `isFlipped` argument to `false`.

### Before 

```swift
var predictedPoints = postProcessor.convertToPredictedPoints(from: heatmaps, isFlipped: true)
```

### After

```swift
var predictedPoints = postProcessor.convertToPredictedPoints(from: heatmaps, isFlipped: false)
```
