### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by oslearningbear** [tucan9389/PoseEstimation-CoreML#26]
Keep running into

```
Unknown class _TtC21PoseEstimation_CoreML19JointViewController in Interface Builder file.
```
Error

Tried running on Iphone 6 and Iphone 11 simulators

**Comment by tucan9389** [comment]
@oslearningbear 
What is your Xcode version?

**Comment by oslearningbear** [comment]
I got it working after migrating to swift5 via xcode. On Xcode 11.3.1

**Comment by tucan9389** [comment]
@oslearningbear 
Nice. What is your previous Xcode version and swift version? If you share, other people would be helped.
